name: flutter_ca_tdd
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  Service locator
  get_it: ^7.6.0
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  # Remote API
  connectivity_plus: ^4.0.1
  http: ^1.1.0
  # Local cache
  shared_preferences: ^2.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
